#Numpy Arrays

In [1]:
import numpy as np

In [65]:
x=np.array([1,2,3,4])        #int
print(x)
print(type(x))
print(x.dtype)
y=np.array([1.2,2,3,4])      #float
print(y)
print(type(y))
print(y.dtype)
z=np.array(["a",1,2,3,4])    #character
print(z)
print(type(z))
print(z.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int32
[1.2 2.  3.  4. ]
<class 'numpy.ndarray'>
float64
['a' '1' '2' '3' '4']
<class 'numpy.ndarray'>
<U11


In [19]:
a=np.array([10,20,30,40])
print(a)
print(type(a))
print(a.shape)

[10 20 30 40]
<class 'numpy.ndarray'>
(4,)


In [29]:
c = np.arange(1,5)
print(a)
type(a)

[10 20 30 40]


numpy.ndarray

In [41]:
a=np.array([1,2,3,4])
np.sqrt(a)

array([1, 2, 3, 4])

In [43]:
np.around(a)

array([1, 2, 3, 4])

In [47]:
a1=np.array([[3,4,5,6],[37,8,9,np.NAN]])
a1_copy1=a1.astype(float)
a1_copy1.dtype

dtype('float64')

In [49]:
a1=np.array([[3,4,5,6],[37,8,9,np.NAN]])
print(a1)
a1.dtype

[[ 3.  4.  5.  6.]
 [37.  8.  9. nan]]


dtype('float64')

In [53]:
a1_copy1=a1.astype(str)
print(a1_copy1)
a1_copy1.dtype

[['3.0' '4.0' '5.0' '6.0']
 ['37.0' '8.0' '9.0' 'nan']]


dtype('<U32')

In [ ]:
#Mathematical operations on rows and columns

In [55]:
b=np.array([[3,4,6],[7,9,10],[4,6,12]])
b

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [59]:
print(b.sum(axis=1))
print(b.sum(axis=0))

[13 26 22]
[14 19 28]


In [67]:
print(np.mean(b, axis=1))
print(np.mean(b, axis=0))

[4.33333333 8.66666667 7.33333333]
[4.66666667 6.33333333 9.33333333]


#Matrix operations

In [69]:
a3=np.array([[3,4,5],[5,6,7],[8,9,0]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [5 6 7]
 [8 9 0]]
[[0 4 5]
 [5 0 7]
 [8 9 0]]


In [83]:
#Matrix multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.matmul(A, B)
print(C)

[[19 22]
 [43 50]]


In [85]:
#Transpose of the matrices
print(A.T)
print(B.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [97]:
#Accessing the array elements
a4=np.array([[3,4,5],[7,2,8],[9,1,6],[10,9,18]])
a4

array([[ 3,  4,  5],
       [ 7,  2,  8],
       [ 9,  1,  6],
       [10,  9, 18]])

In [99]:
a4[3][2]

18

In [89]:
#Slicing of array
a4[0::3,0::2]

array([[ 3,  5],
       [10, 18]])

In [91]:
a4[[0,3]]

array([[ 3,  4,  5],
       [10,  9, 18]])

In [101]:
a4[:,1:]

array([[ 4,  5],
       [ 2,  8],
       [ 1,  6],
       [ 9, 18]])

In [115]:
a4[1:3,0:2]

array([[7, 2],
       [9, 1]])